# Generated by Django 5.2 on 2026-07-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(default="null", upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(max_length=260),
        ),
    ]
